apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: promtail
      version: 6.17.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    config:
      clients:
        - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
      snippets:
        pipelineStages:
          - cri: {}
          - match:
              selector: '{namespace="cloudflared", app="cloudflared"}'
              stages:
                - drop:
                    expression: 'stream [0-9]+ canceled by remote with error code 0'
          - match:
              selector: '{namespace="kube-system", app="kube-apiserver"}'
              stages:
                - drop:
                    expression: 'addrConn\\.createTransport failed to connect to .*2379.*operation was canceled'
        extraRelabelConfigs:
          - action: replace
            source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
