apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wow-data
  namespace: wow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi

