apiVersion: batch/v1
kind: CronJob
metadata:
  name: wow-db-sync
  namespace: wow
spec:
  # Suspended by default; run manually when ready:
  # kubectl -n wow create job --from=cronjob/wow-db-sync wow-db-sync-1
  suspend: true
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: work
              emptyDir: {}
          initContainers:
            - name: clone-base
              image: alpine/git:2.47.2
              env:
                - name: WOW_BASE_DB_REPO
                  value: https://github.com/mangoszero/database.git
                - name: WOW_BASE_DB_REF
                  value: master
              command:
                - sh
                - -lc
                - |
                  set -eu
                  rm -rf /work/base
                  git clone --depth=1 --branch "${WOW_BASE_DB_REF}" "${WOW_BASE_DB_REPO}" /work/base
              volumeMounts:
                - name: work
                  mountPath: /work
            - name: clone-realm
              image: alpine/git:2.47.2
              env:
                - name: WOW_REALM_DB_REPO
                  value: https://github.com/mangos/Realm_DB.git
                - name: WOW_REALM_DB_REF
                  value: master
              command:
                - sh
                - -lc
                - |
                  set -eu
                  rm -rf /work/realm
                  git clone --depth=1 --branch "${WOW_REALM_DB_REF}" "${WOW_REALM_DB_REPO}" /work/realm
              volumeMounts:
                - name: work
                  mountPath: /work
            - name: clone-custom
              image: alpine/git:2.47.2
              env:
                - name: WOW_CUSTOM_DB_REPO
                  value: https://github.com/RovxBot/1.12.1-database.git
                - name: WOW_CUSTOM_DB_REF
                  value: master
              command:
                - sh
                - -lc
                - |
                  set -eu
                  rm -rf /work/custom
                  git clone --depth=1 --branch "${WOW_CUSTOM_DB_REF}" "${WOW_CUSTOM_DB_REPO}" /work/custom
              volumeMounts:
                - name: work
                  mountPath: /work
          containers:
            - name: mariadb-client
              image: mariadb:11.4
              env:
                - name: DB_HOST
                  value: wow-mariadb.wow.svc.cluster.local
                - name: DB_PORT
                  value: "3306"
                - name: DB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: wow-mariadb-auth
                      key: MARIADB_ROOT_PASSWORD
                # Custom repo layout (migrations only; base schema/data comes from upstream):
                - name: WOW_CUSTOM_MIGRATIONS_DIR
                  value: /work/custom/migrations
                # Vanilla DB names (match upstream defaults).
                - name: WOW_REALM_DB
                  value: realmd
                - name: WOW_WORLD_DB
                  value: mangos0
                - name: WOW_CHAR_DB
                  value: character0
                # Realm entry (for LAN NodePort access via metal7)
                - name: WOW_REALM_ID
                  value: "1"
                - name: WOW_REALM_NAME
                  value: "cooked.beer (vanilla)"
                - name: WOW_REALM_ADDRESS
                  value: "192.168.1.197"
                - name: WOW_REALM_PORT
                  value: "30085"
                - name: WOW_REALM_BUILDS
                  value: "5875"
                - name: WOW_DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: wow-mariadb-auth
                      key: MARIADB_USER
                - name: WOW_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: wow-mariadb-auth
                      key: MARIADB_PASSWORD
              command:
                - sh
                - -lc
                - |
                  set -eu

                  db() {
                    command mariadb \
                      --protocol=tcp \
                      --host "${DB_HOST}" \
                      --port "${DB_PORT}" \
                      --user root \
                      --password="${DB_ROOT_PASSWORD}" \
                      "$@"
                  }

                  echo "Waiting for MariaDB at ${DB_HOST}:${DB_PORT}..."
                  for _ in $(seq 1 120); do
                    if db --execute "SELECT 1" >/dev/null 2>&1; then
                      break
                    fi
                    sleep 2
                  done

                  ensure_db() {
                    dbname="$1"
                    db --execute "CREATE DATABASE IF NOT EXISTS \`${dbname}\`;"
                  }

                  drop_db() {
                    dbname="$1"
                    db --execute "DROP DATABASE IF EXISTS \`${dbname}\`;"
                    db --execute "CREATE DATABASE \`${dbname}\`;"
                  }

                  ensure_user_grants() {
                    # Ensure the app user can access all DBs (idempotent).
                    db --execute "CREATE USER IF NOT EXISTS '${WOW_DB_USER}'@'%' IDENTIFIED BY '${WOW_DB_PASSWORD}';"
                    db --execute "GRANT ALL PRIVILEGES ON \`${WOW_REALM_DB}\`.* TO '${WOW_DB_USER}'@'%';"
                    db --execute "GRANT ALL PRIVILEGES ON \`${WOW_WORLD_DB}\`.* TO '${WOW_DB_USER}'@'%';"
                    db --execute "GRANT ALL PRIVILEGES ON \`${WOW_CHAR_DB}\`.* TO '${WOW_DB_USER}'@'%';"
                    db --execute "FLUSH PRIVILEGES;"
                  }

                  has_db_version() {
                    dbname="$1"
                    db --database "${dbname}" --skip-column-names --batch --execute \
                      "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${dbname}' AND table_name='db_version';" 2>/dev/null || echo "0"
                  }

                  bootstrap_sql_dump() {
                    dbname="$1"
                    dump_file="$2"
                    workdir="$3"
                    echo "Bootstrapping ${dbname} from ${dump_file}..."
                    (cd "${workdir}" && db --database "${dbname}" < "${dump_file}")
                  }

                  ensure_realm_db() {
                    if [ "$(has_db_version "${WOW_REALM_DB}")" -eq 0 ]; then
                      echo "Realm DB missing db_version; recreating ${WOW_REALM_DB}..."
                      drop_db "${WOW_REALM_DB}"
                      bootstrap_sql_dump "${WOW_REALM_DB}" "Setup/realmdLoadDB.sql" "/work/realm"
                    else
                      echo "Realm DB already has db_version; leaving as-is."
                    fi
                  }

                  ensure_world_db() {
                    if [ "$(has_db_version "${WOW_WORLD_DB}")" -eq 0 ]; then
                      echo "World DB missing db_version; recreating ${WOW_WORLD_DB}..."
                      drop_db "${WOW_WORLD_DB}"
                      bootstrap_sql_dump "${WOW_WORLD_DB}" "World/Setup/mangosdLoadDB.sql" "/work/base"
                    else
                      echo "World DB already has db_version; leaving as-is."
                    fi
                  }

                  ensure_char_db() {
                    if [ "$(has_db_version "${WOW_CHAR_DB}")" -eq 0 ]; then
                      echo "Character DB missing db_version; recreating ${WOW_CHAR_DB}..."
                      drop_db "${WOW_CHAR_DB}"
                      bootstrap_sql_dump "${WOW_CHAR_DB}" "Character/Setup/characterLoadDB.sql" "/work/base"
                    else
                      echo "Character DB already has db_version; leaving as-is."
                    fi
                  }

                  ensure_db "${WOW_REALM_DB}"
                  ensure_db "${WOW_WORLD_DB}"
                  ensure_db "${WOW_CHAR_DB}"
                  ensure_user_grants

                  ensure_realm_db
                  ensure_world_db
                  ensure_char_db

                  # Ensure the realm list table exists (some bootstrap sets may omit it).
                  realm_table_count="$(db --database "${WOW_REALM_DB}" --skip-column-names --batch --execute "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${WOW_REALM_DB}' AND table_name='realmlist';")"
                  if [ "${realm_table_count}" -eq 0 ]; then
                    echo "realmlist table not found in ${WOW_REALM_DB}; creating minimal schema..."
                    db --database "${WOW_REALM_DB}" --execute "CREATE TABLE IF NOT EXISTS realmlist (id INT UNSIGNED NOT NULL DEFAULT 0, name VARCHAR(32) NOT NULL DEFAULT '', address VARCHAR(255) NOT NULL DEFAULT '127.0.0.1', port SMALLINT UNSIGNED NOT NULL DEFAULT 8085, icon TINYINT UNSIGNED NOT NULL DEFAULT 0, realmflags TINYINT UNSIGNED NOT NULL DEFAULT 0, timezone TINYINT UNSIGNED NOT NULL DEFAULT 0, allowedSecurityLevel TINYINT UNSIGNED NOT NULL DEFAULT 0, population FLOAT NOT NULL DEFAULT 0, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
                  fi

                  # Ensure realm record points to the LAN node/port (idempotent).
                  db --database "${WOW_REALM_DB}" --execute "INSERT INTO realmlist (id, name, address, port, realmbuilds) VALUES (${WOW_REALM_ID}, '${WOW_REALM_NAME}', '${WOW_REALM_ADDRESS}', ${WOW_REALM_PORT}, '${WOW_REALM_BUILDS}') ON DUPLICATE KEY UPDATE name=VALUES(name), address=VALUES(address), port=VALUES(port), realmbuilds=VALUES(realmbuilds);"

                  # Apply custom migrations to world DB (gates/tweaks live here).
                  if [ -d "${WOW_CUSTOM_MIGRATIONS_DIR}" ]; then
                    echo "Applying world migrations from ${WOW_CUSTOM_MIGRATIONS_DIR}..."
                    find "${WOW_CUSTOM_MIGRATIONS_DIR}" -maxdepth 1 -type f -name '*.sql' -print | sort | while read -r f; do
                      echo "Applying migration: ${f##*/}"
                      db --database "${WOW_WORLD_DB}" < "$f"
                    done
                  else
                    echo "No migrations dir found at ${WOW_CUSTOM_MIGRATIONS_DIR}; nothing to do."
                  fi
              volumeMounts:
                - name: work
                  mountPath: /work
