apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wow-mariadb-data
  namespace: wow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi

