apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wow-mariadb
  namespace: wow
spec:
  serviceName: wow-mariadb
  replicas: 1
  selector:
    matchLabels:
      app: wow-mariadb
  template:
    metadata:
      labels:
        app: wow-mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.4
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wow-mariadb-auth
                  key: MARIADB_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: wow-mariadb-auth
                  key: MARIADB_DATABASE
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: wow-mariadb-auth
                  key: MARIADB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wow-mariadb-auth
                  key: MARIADB_PASSWORD
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 4Gi
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wow-mariadb-data

