---
# NFS PV for emby_media on NAS #1 (192.168.1.153)
# Contains: Movies
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-emby-media
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=3
    - nolock
  nfs:
    server: 192.168.1.153
    path: /volume1/emby_media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-emby-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  volumeName: nfs-emby-media
  resources:
    requests:
      storage: 10Ti
