apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wotlk-mariadb
spec:
  serviceName: wotlk-mariadb
  replicas: 1
  selector:
    matchLabels:
      app: wotlk-mariadb
  template:
    metadata:
      labels:
        app: wotlk-mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.4
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wotlk-mariadb-auth
                  key: MARIADB_ROOT_PASSWORD
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: wotlk-mariadb-auth
                  key: MARIADB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wotlk-mariadb-auth
                  key: MARIADB_PASSWORD
            - name: MARIADB_ROOT_HOST
              value: "%"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wotlk-mariadb-data
