apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wotlk-mariadb
spec:
  serviceName: wotlk-mariadb
  replicas: 1
  selector:
    matchLabels:
      app: wotlk-mariadb
  template:
    metadata:
      labels:
        app: wotlk-mariadb
    spec:
      priorityClassName: wotlk-critical
      containers:
        - name: mysql
          image: mysql:8.0
          resources:
            requests:
              cpu: 200m
              memory: 2Gi
            limits:
              cpu: "2"
              memory: 6Gi
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wotlk-mariadb-auth
                  key: MARIADB_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: wotlk-mariadb-auth
                  key: MARIADB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wotlk-mariadb-auth
                  key: MARIADB_PASSWORD
            - name: MYSQL_ROOT_HOST
              value: "%"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wotlk-mariadb-data
