apiVersion: batch/v1
kind: CronJob
metadata:
  name: wotlk-playerbots-normalize-ascii
  namespace: wotlk
spec:
  # Suspended by default; run manually when needed:
  # kubectl -n wotlk create job --from=cronjob/wotlk-playerbots-normalize-ascii wotlk-playerbots-normalize-ascii-1
  suspend: true
  schedule: "0 4 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: scripts
              configMap:
                name: wotlk-playerbots-normalize-ascii-sql
          containers:
            - name: mariadb-client
              image: mysql:8.0
              env:
                - name: DB_HOST
                  value: wotlk-mariadb.wotlk.svc.cluster.local
                - name: DB_PORT
                  value: "3306"
                - name: DB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: wotlk-mariadb-auth
                      key: MARIADB_ROOT_PASSWORD
              command:
                - sh
                - -lc
                - |
                  set -euo pipefail

                  db() {
                    command mysql \
                      --protocol=tcp \
                      --host "${DB_HOST}" \
                      --port "${DB_PORT}" \
                      --user root \
                      --password="${DB_ROOT_PASSWORD}" \
                      --ssl-mode=DISABLED \
                      --get-server-public-key \
                      "$@"
                  }

                  echo "Waiting for MySQL at ${DB_HOST}:${DB_PORT}..."
                  for _ in $(seq 1 240); do
                    if db --execute "SELECT 1" >/dev/null 2>&1; then
                      break
                    fi
                    sleep 2
                  done

                  echo "Normalizing playerbot text punctuation..."
                  db < /scripts/playerbots-normalize-ascii.sql

                  echo "Done."
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
                  readOnly: true

