apiVersion: batch/v1
kind: CronJob
metadata:
  name: wotlk-tokenstore-dailies
  namespace: wotlk
spec:
  # Runs daily to ensure token item + quest wiring exists.
  schedule: "0 0 * * *"
  timeZone: Australia/Adelaide
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: tokenstore-dailies
              image: alpine:3.20
              env:
                - name: DB_HOST
                  value: wotlk-mariadb.wotlk.svc.cluster.local
                - name: DB_PORT
                  value: "3306"
                - name: DB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: wotlk-mariadb-auth
                      key: MARIADB_ROOT_PASSWORD
              command:
                - sh
                - -lc
                - |
                  set -euo pipefail

                  apk add --no-cache mariadb-client >/dev/null

                  db() {
                    command mysql \
                      --protocol=tcp \
                      --host "${DB_HOST}" \
                      --port "${DB_PORT}" \
                      --user root \
                      --password="${DB_ROOT_PASSWORD}" \
                      --ssl-mode=DISABLED \
                      --get-server-public-key \
                      "$@"
                  }

                  TOKEN_ITEM_ID="${TOKEN_ITEM_ID:-90000}"
                  CLASSIC_DUTY_ITEM_ID="${CLASSIC_DUTY_ITEM_ID:-90001}"
                  TBC_DUTY_ITEM_ID="${TBC_DUTY_ITEM_ID:-90002}"

                  QUEST_CLASSIC_ID="${QUEST_CLASSIC_ID:-210010}"
                  QUEST_TBC_ID="${QUEST_TBC_ID:-210011}"

                  DUTY_NPC_ALLIANCE="${DUTY_NPC_ALLIANCE:-900100}"
                  DUTY_NPC_HORDE="${DUTY_NPC_HORDE:-900101}"

                  # Existing auctioneers used previously as quest givers (we remove any quest links from them).
                  AUCTIONEER_ALLIANCE="${AUCTIONEER_ALLIANCE:-15659}" # Auctioneer Jaxon (Stormwind)
                  AUCTIONEER_HORDE="${AUCTIONEER_HORDE:-8724}"       # Auctioneer Wabang (Orgrimmar)

                  # Exclude known raid end-bosses (these values match instance_encounters.lastEncounterDungeon in your DB).
                  EXCLUDE_CLASSIC_RAID_DUNGEON_IDS="42,48,50,160,161"
                  EXCLUDE_TBC_RAID_DUNGEON_IDS="175,176,177,193,194,195,196,197,198,199,201"

                  # WotLK heroic "Proof of Demise" quest IDs (end-boss daily series).
                  # These already exist in the DB; we just ensure they reward tokens.
                  HEROIC_PROOF_QUESTS="13245,13246,13247,13248,13249,13250,13251,13252,13253,13254,13255,13256,14199"

                  echo "Ensuring token + duty items exist..."
                  db --database acore_world --execute "
                    INSERT IGNORE INTO item_template
                      (entry, class, subclass, name, displayid, Quality, bonding, stackable, maxcount, BuyPrice, SellPrice, description)
                    VALUES
                      (${TOKEN_ITEM_ID}, 10, 0, 'Grim Token', 64062, 2, 1, 1000, 0, 0, 1, 'Earned from daily dungeon quests. Used for vanity rewards in the portal store.'),
                      (${CLASSIC_DUTY_ITEM_ID}, 12, 0, 'Dungeon Duty Mark', 134944, 1, 1, 1, 1, 0, 0, 'Taken from the final boss of any classic dungeon.'),
                      (${TBC_DUTY_ITEM_ID}, 12, 0, 'Faction Service Mark', 134944, 1, 1, 1, 1, 0, 0, 'Taken from the final boss of any Outland dungeon.');

                    UPDATE item_template
                      SET bonding = 1, SellPrice = 1, BuyPrice = 0, stackable = 1000
                      WHERE entry = ${TOKEN_ITEM_ID};
                  "

                  echo "Ensuring heroic proof quests reward 5 tokens..."
                  db --database acore_world --execute "
                    UPDATE quest_template
                      SET RewardItem1 = ${TOKEN_ITEM_ID}, RewardAmount1 = 5
                      WHERE ID IN (${HEROIC_PROOF_QUESTS});
                  "

                  echo "Ensuring dedicated questgiver NPCs exist (SW/Org)..."
                  db --database acore_world --execute "
                    INSERT INTO creature_template
                      (entry, difficulty_entry_1, difficulty_entry_2, difficulty_entry_3, KillCredit1, KillCredit2, name, subname, IconName,
                       gossip_menu_id, minlevel, maxlevel, exp, faction, npcflag, speed_walk, speed_run, speed_swim, speed_flight,
                       detection_range, scale, rank, dmgschool, DamageModifier, BaseAttackTime, RangeAttackTime, BaseVariance, RangeVariance,
                       unit_class, unit_flags, unit_flags2, dynamicflags, family, trainer_type, trainer_spell, trainer_class, trainer_race,
                       type, type_flags, lootid, pickpocketloot, skinloot, PetSpellDataId, VehicleId, mingold, maxgold, AIName, MovementType,
                       HoverHeight, HealthModifier, ManaModifier, ArmorModifier, ExperienceModifier, RacialLeader, movementId, RegenHealth,
                       mechanic_immune_mask, spell_school_immune_mask, flags_extra, ScriptName, VerifiedBuild)
                    SELECT
                      ${DUTY_NPC_ALLIANCE},
                      difficulty_entry_1, difficulty_entry_2, difficulty_entry_3, KillCredit1, KillCredit2,
                      'Grim Token Envoy', 'Daily Dungeon Rewards', IconName,
                      gossip_menu_id, minlevel, maxlevel, exp, faction,
                      2,
                      speed_walk, speed_run, speed_swim, speed_flight,
                      detection_range, scale, rank, dmgschool, DamageModifier, BaseAttackTime, RangeAttackTime, BaseVariance, RangeVariance,
                      unit_class, unit_flags, unit_flags2, dynamicflags, family, trainer_type, trainer_spell, trainer_class, trainer_race,
                      type, type_flags, lootid, pickpocketloot, skinloot, PetSpellDataId, VehicleId, mingold, maxgold, AIName, MovementType,
                      HoverHeight, HealthModifier, ManaModifier, ArmorModifier, ExperienceModifier, RacialLeader, movementId, RegenHealth,
                      mechanic_immune_mask, spell_school_immune_mask, flags_extra, ScriptName, VerifiedBuild
                    FROM creature_template
                    WHERE entry = ${AUCTIONEER_ALLIANCE}
                      AND NOT EXISTS (SELECT 1 FROM creature_template WHERE entry = ${DUTY_NPC_ALLIANCE});

                    INSERT INTO creature_template
                      (entry, difficulty_entry_1, difficulty_entry_2, difficulty_entry_3, KillCredit1, KillCredit2, name, subname, IconName,
                       gossip_menu_id, minlevel, maxlevel, exp, faction, npcflag, speed_walk, speed_run, speed_swim, speed_flight,
                       detection_range, scale, rank, dmgschool, DamageModifier, BaseAttackTime, RangeAttackTime, BaseVariance, RangeVariance,
                       unit_class, unit_flags, unit_flags2, dynamicflags, family, trainer_type, trainer_spell, trainer_class, trainer_race,
                       type, type_flags, lootid, pickpocketloot, skinloot, PetSpellDataId, VehicleId, mingold, maxgold, AIName, MovementType,
                       HoverHeight, HealthModifier, ManaModifier, ArmorModifier, ExperienceModifier, RacialLeader, movementId, RegenHealth,
                       mechanic_immune_mask, spell_school_immune_mask, flags_extra, ScriptName, VerifiedBuild)
                    SELECT
                      ${DUTY_NPC_HORDE},
                      difficulty_entry_1, difficulty_entry_2, difficulty_entry_3, KillCredit1, KillCredit2,
                      'Grim Token Envoy', 'Daily Dungeon Rewards', IconName,
                      gossip_menu_id, minlevel, maxlevel, exp, faction,
                      2,
                      speed_walk, speed_run, speed_swim, speed_flight,
                      detection_range, scale, rank, dmgschool, DamageModifier, BaseAttackTime, RangeAttackTime, BaseVariance, RangeVariance,
                      unit_class, unit_flags, unit_flags2, dynamicflags, family, trainer_type, trainer_spell, trainer_class, trainer_race,
                      type, type_flags, lootid, pickpocketloot, skinloot, PetSpellDataId, VehicleId, mingold, maxgold, AIName, MovementType,
                      HoverHeight, HealthModifier, ManaModifier, ArmorModifier, ExperienceModifier, RacialLeader, movementId, RegenHealth,
                      mechanic_immune_mask, spell_school_immune_mask, flags_extra, ScriptName, VerifiedBuild
                    FROM creature_template
                    WHERE entry = ${AUCTIONEER_HORDE}
                      AND NOT EXISTS (SELECT 1 FROM creature_template WHERE entry = ${DUTY_NPC_HORDE});
                  "

                  db --database acore_world --execute "
                    INSERT INTO creature
                      (id1, id2, id3, map, zoneId, areaId, spawnMask, phaseMask, equipment_id,
                       position_x, position_y, position_z, orientation,
                       spawntimesecs, wander_distance, currentwaypoint,
                       curhealth, curmana, MovementType, npcflag, unit_flags, dynamicflags, ScriptName, VerifiedBuild, CreateObject, Comment)
                    SELECT
                      ${DUTY_NPC_ALLIANCE}, id2, id3, map, zoneId, areaId, spawnMask, phaseMask, equipment_id,
                      position_x + 2.0, position_y + 0.5, position_z, orientation,
                      spawntimesecs, 0, currentwaypoint,
                      curhealth, curmana, MovementType, 0, unit_flags, dynamicflags, ScriptName, VerifiedBuild, CreateObject, 'Grim token questgiver (SW)'
                    FROM creature
                    WHERE id1 = ${AUCTIONEER_ALLIANCE}
                      AND NOT EXISTS (SELECT 1 FROM creature WHERE id1 = ${DUTY_NPC_ALLIANCE})
                    ORDER BY guid
                    LIMIT 1;

                    INSERT INTO creature
                      (id1, id2, id3, map, zoneId, areaId, spawnMask, phaseMask, equipment_id,
                       position_x, position_y, position_z, orientation,
                       spawntimesecs, wander_distance, currentwaypoint,
                       curhealth, curmana, MovementType, npcflag, unit_flags, dynamicflags, ScriptName, VerifiedBuild, CreateObject, Comment)
                    SELECT
                      ${DUTY_NPC_HORDE}, id2, id3, map, zoneId, areaId, spawnMask, phaseMask, equipment_id,
                      position_x + 2.0, position_y + 0.5, position_z, orientation,
                      spawntimesecs, 0, currentwaypoint,
                      curhealth, curmana, MovementType, 0, unit_flags, dynamicflags, ScriptName, VerifiedBuild, CreateObject, 'Grim token questgiver (Org)'
                    FROM creature
                    WHERE id1 = ${AUCTIONEER_HORDE}
                      AND NOT EXISTS (SELECT 1 FROM creature WHERE id1 = ${DUTY_NPC_HORDE})
                    ORDER BY guid
                    LIMIT 1;
                  "

                  echo "Upserting bracket dailies (classic + Outland)..."
                  db --database acore_world --execute "
                    INSERT INTO quest_template
                      (ID, QuestType, QuestLevel, MinLevel, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags,
                       RewardItem1, RewardAmount1,
                       RequiredItemId1, RequiredItemCount1,
                       LogTitle, LogDescription, QuestDescription, QuestCompletionLog,
                       ObjectiveText1)
                    VALUES
                      (
                      ${QUEST_CLASSIC_ID},
                      2,
                      60,
                      15,
                      0,
                      0,
                      5,
                      4224,
                      ${TOKEN_ITEM_ID},
                      1,
                      ${CLASSIC_DUTY_ITEM_ID},
                      1,
                      'Doing Your Duty',
                      'Complete any classic dungeon via the Dungeon Finder and claim your daily token.',
                      'Enter any classic dungeon and defeat its final boss. Loot a Dungeon Duty Mark as proof, then return for your reward.',
                      'Duty complete.',
                      'Acquire a Dungeon Duty Mark.'
                      ),
                      (
                      ${QUEST_TBC_ID},
                      2,
                      70,
                      61,
                      0,
                      0,
                      5,
                      4224,
                      ${TOKEN_ITEM_ID},
                      2,
                      ${TBC_DUTY_ITEM_ID},
                      1,
                      'Service to Your Faction',
                      'Complete any Outland dungeon via the Dungeon Finder and claim your daily tokens.',
                      'Enter any Outland dungeon and defeat its final boss. Loot a Faction Service Mark as proof, then return for your reward.',
                      'Service complete.',
                      'Acquire a Faction Service Mark.'
                      )
                    ON DUPLICATE KEY UPDATE
                      RewardItem1 = VALUES(RewardItem1),
                      RewardAmount1 = VALUES(RewardAmount1),
                      RequiredItemId1 = VALUES(RequiredItemId1),
                      RequiredItemCount1 = VALUES(RequiredItemCount1),
                      Flags = VALUES(Flags),
                      ObjectiveText1 = VALUES(ObjectiveText1);
                  "

                  echo "Linking bracket dailies to quest givers..."
                  db --database acore_world --execute "
                    DELETE FROM creature_queststarter
                      WHERE quest IN (${QUEST_CLASSIC_ID}, ${QUEST_TBC_ID})
                        AND id IN (${AUCTIONEER_ALLIANCE}, ${AUCTIONEER_HORDE});
                    DELETE FROM creature_questender
                      WHERE quest IN (${QUEST_CLASSIC_ID}, ${QUEST_TBC_ID})
                        AND id IN (${AUCTIONEER_ALLIANCE}, ${AUCTIONEER_HORDE});

                    INSERT IGNORE INTO creature_queststarter (id, quest) VALUES
                      (${DUTY_NPC_ALLIANCE}, ${QUEST_CLASSIC_ID}),
                      (${DUTY_NPC_HORDE}, ${QUEST_CLASSIC_ID}),
                      (${DUTY_NPC_ALLIANCE}, ${QUEST_TBC_ID}),
                      (${DUTY_NPC_HORDE}, ${QUEST_TBC_ID});

                    INSERT IGNORE INTO creature_questender (id, quest) VALUES
                      (${DUTY_NPC_ALLIANCE}, ${QUEST_CLASSIC_ID}),
                      (${DUTY_NPC_HORDE}, ${QUEST_CLASSIC_ID}),
                      (${DUTY_NPC_ALLIANCE}, ${QUEST_TBC_ID}),
                      (${DUTY_NPC_HORDE}, ${QUEST_TBC_ID});
                  "

                  echo "Ensuring final bosses drop duty marks (quest-required loot)..."
                  db --database acore_world --execute "
                    WITH classic AS (
                      SELECT DISTINCT ie.creditEntry AS boss_entry
                      FROM instance_encounters ie
                      JOIN creature_template ct ON ct.entry = ie.creditEntry
                      WHERE ie.lastEncounterDungeon != 0
                        AND ie.creditType = 0
                        AND ct.exp = 0
                        AND ie.lastEncounterDungeon NOT IN (${EXCLUDE_CLASSIC_RAID_DUNGEON_IDS})
                    )
                    INSERT IGNORE INTO creature_loot_template
                      (Entry, Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount, Comment)
                    SELECT
                      boss_entry, ${CLASSIC_DUTY_ITEM_ID}, 0, 100, 1, 1, 0, 1, 1, 'Grim classic duty mark'
                    FROM classic;
                  "

                  db --database acore_world --execute "
                    WITH tbc AS (
                      SELECT DISTINCT ie.creditEntry AS boss_entry
                      FROM instance_encounters ie
                      JOIN creature_template ct ON ct.entry = ie.creditEntry
                      WHERE ie.lastEncounterDungeon != 0
                        AND ie.creditType = 0
                        AND ct.exp = 1
                        AND ie.lastEncounterDungeon NOT IN (${EXCLUDE_TBC_RAID_DUNGEON_IDS})
                    )
                    INSERT IGNORE INTO creature_loot_template
                      (Entry, Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount, Comment)
                    SELECT
                      boss_entry, ${TBC_DUTY_ITEM_ID}, 0, 100, 1, 1, 0, 1, 1, 'Grim TBC duty mark'
                    FROM tbc;
                  "

                  echo "Done. Counts:"
                  db --database acore_world --execute "
                    SELECT 'token_item' AS k, COUNT(*) AS v FROM item_template WHERE entry = ${TOKEN_ITEM_ID}
                    UNION ALL SELECT 'classic_daily' AS k, COUNT(*) AS v FROM quest_template WHERE ID = ${QUEST_CLASSIC_ID}
                    UNION ALL SELECT 'tbc_daily' AS k, COUNT(*) AS v FROM quest_template WHERE ID = ${QUEST_TBC_ID};
                  "
