apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-immich-uploads
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
  nfs:
    server: 192.168.1.154
    path: "/volume1/Plex Media/images"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-immich-uploads
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 10Ti
  volumeName: nfs-immich-uploads
