apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-immich-model-cache
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.1.184
    path: "/export/appdata/immich/model-cache"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-immich-model-cache
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi
  volumeName: nfs-immich-model-cache
