apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkyfitness-frontend
  namespace: sparkyfitness
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sparkyfitness-frontend
  template:
    metadata:
      labels:
        app: sparkyfitness-frontend
    spec:
      containers:
        - name: sparkyfitness-frontend
          image: codewithcj/sparkyfitness:v0.16.3.3@sha256:12c2804b14946289130555a62d772a691c7b35a88ce4db3f298c3962a99b4595
          imagePullPolicy: IfNotPresent
          env:
            - name: SPARKY_FITNESS_SERVER_HOST
              value: sparkyfitness-server
            - name: SPARKY_FITNESS_SERVER_PORT
              value: "3010"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sparkyfitness-frontend
  namespace: sparkyfitness
spec:
  selector:
    app: sparkyfitness-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
