apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparkyfitness-postgres
  namespace: sparkyfitness
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkyfitness-postgres
  namespace: sparkyfitness
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sparkyfitness-postgres
  template:
    metadata:
      labels:
        app: sparkyfitness-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: sparkyfitness_db
            - name: POSTGRES_USER
              value: sparky
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sparkyfitness-secrets
                  key: SPARKY_FITNESS_DB_PASSWORD
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sparkyfitness-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: sparkyfitness-postgres
  namespace: sparkyfitness
spec:
  selector:
    app: sparkyfitness-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

