apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: metal7
  namespace: longhorn-system
spec:
  disks:
    default-disk-081400000000:
      allowScheduling: true
      diskType: filesystem
      path: /var/lib/longhorn/
      storageReserved: 37697460633
    extra-disk:
      allowScheduling: true
      diskType: filesystem
      path: /var/lib/longhorn/extra
      storageReserved: 21474836480
