apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cloudflare-ddns
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:1F0Ch/3KKQydXw==,iv:DjhUhpF6dWQ8WI7ICwPhp9KZqpNM/0qScx9tsMNPy4I=,tag:ABMGk23miI5M+QYE0LaDFw==,type:str]
sops:
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaTNiM1A0dHp5WGwzOGJU
            OGVCcXR3VE90SHpPajYrT3hONXVtcEZhUWlnClFOVnBULzhFVHVrRStjYzM0YmpM
            cExDSGZHalo2c1FOOXBUNzdFY2hHQ0kKLS0tIFU1K1BMeWRNcUd6L0o5UDVMYWxl
            RUFrVVZneXAxZ2MvTGZKUUQrMkZBYlEKKMokfPXvX77Dc9saHTfy/zFzvJGvmLd8
            hXRKPaiyjIzU/p4G3ztCspe6ZjgVZfENWvSzWHwDvDjj/aRXYksMsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T02:51:05Z"
    mac: ENC[AES256_GCM,data:uUNFvDYnar6R4Ih2k1kushwboEoNm85UoSNOuJ2a2hZiRgA17jbE+fBTL8cLTH1Luga7EIJkN8iy5w0JFvNb3u3wrQ8sNzUJ5Oc4KOccMDp2VONHsVnHOnoMgOYAMLnxeLGGNQZFNKbanExTmoxWTKq7NGJTjcJlYdFk/H+NqbE=,iv:bJRcsNB7CFamsJGC1WYFQjmE6ODwsfv0LzpoyKkDHcU=,tag:A0QI2eogoAzD7kfAvJHv5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
