apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:MRJy1BL1mHI=,iv:FZoxw+sa40AYTAn9r7LdGsQuTktw4dd3X3NZAXGvwNA=,tag:/oTJZLurY7owExLSJJUi3A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:fC8k/1RytDw=,iv:U3vwRyTyYkCsF0vp9qO3YWFjGpWtu4xXuNub2XPd9t0=,tag:a6FvqC2MswYaelaNqEy0CA==,type:str]
sops:
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVajhLeUFFeDZlMkdHVllB
            OEJ4MG91djNtSlM0dEVmTlU0NUR0d3EvLzBRCktMNFpZaTRNbjFrWFFuS2hON3Jm
            Y1VsdUZRRXRjVDJHTkVYWUtKN2VwSVUKLS0tIFkvMGJVcENPclBtRXErUXg0Wldk
            OVNJVklBMUdKcys5NnZjVHJhSmpVYkEKQd9pSNlGtI29YYKm9RGKar3F8sNDMMHn
            2kA6WMTlxgIDyHtZMJVzWGsHbjwlt8jFjpnXTWawkjLRqhQ1xj5CVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T11:10:24Z"
    mac: ENC[AES256_GCM,data:tY5y7GO1yFeM5Aeo46EubY0Ve03Y/9L2gMahQaLc3clhsFKwa5qu+Ejuum5vI0Z0gJ0hmQG24enxGBjOWU9V2IweYvGDRczzk5ZhlG6aK+WcP6kWvaNdw1XWK643NoNxNsGFHGZ+achbD3rMZWYyDABBI2MTDUBrcjbwZZDZYLc=,iv:guq1jLVqSgf0Cz53+uiM66HtJY7IgRT1uUpcI5WNIY0=,tag:xVIJh97IzyBlSlWn0GX0UA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
